version: "3"

services:
  flaskbb:
    #restart: always
    stdin_open: true
    tty: true
    build: ./dockerfile
    image: flask-deploy:latest
    volumes:
    #  - /home/xuqinghan/dev/flask_test:/code
      - /home/xuqinghan/dev/flaskbb:/code
    ports:
      - "5000:5000"
    #command: gunicorn --workers=1 app:app -b 0.0.0.0:5000
