FROM python
LABEL author="xuqinghan"
LABEL purpose = 'housebook'

RUN apt update
RUN apt install -y nginx gunicorn supervisor

#代码复制过来后的路径
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/requirements.txt
RUN pip3 install -r requirements.txt
ENV PYTHONIOENCODING=utf-8
CMD ["/bin/bash"]
