version: "3"

services:
  flaskbb:
    #restart: always
    stdin_open: true
    tty: true
    build: ./dockerfile
    image: flask-deploy:latest
    volumes:
      - /home/flask_test:/code
    ports:
      - "5000:5000"
    #command: python3 main.py
