#ubuntu-with-python36

#xuqinghan @ 20170903

#ubuntu16.04+python36


FROM ubuntu-with-python36

#python3.6  http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/
#RUN cp ./sources.list /etc/apt/sources.list
#RUN pip install flask

#RUN rm /usr/bin/python3
#RUN ln -s python3.5 /usr/bin/python3